apiVersion: apps/v1
kind: Deployment
metadata:
  name: loader
  namespace: demo
  labels:
    app: loader
spec:
  replicas: 3
  selector:
    matchLabels:
      app: loader
  template:
    metadata:
      labels:
        app: loader
    spec:
      containers:
        - name: loader
          image: busybox
          command:
            - sh
            - -c
            - "while true; do wget -qO- http://api:8080/; done"
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 50m
              memory: 32Mi
