apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 65.1.1
    helm:
      values: |
        prometheus:
          service:
            type: NodePort
          prometheusSpec:
            serviceMonitorSelectorNilUsesHelmValues: false
        alertmanager:
          service:
            type: NodePort
          config:
            global:
              resolve_timeout: 5m
              smtp_smarthost: smtp.gmail.com:587
              smtp_from: quangphongnguyen147@gmail.com
              smtp_auth_username: quangphongnguyen147@gmail.com
              smtp_auth_password: egkvbxkfztxtwfit
            inhibit_rules:
              - equal: ["namespace", "alertname"]
                source_matchers: ["severity = critical"]
                target_matchers: ["severity =~ warning|info"]
              - equal: ["namespace", "alertname"]
                source_matchers: ["severity = warning"]
                target_matchers: ["severity = info"]
              - equal: ["namespace"]
                source_matchers: ["alertname = InfoInhibitor"]
                target_matchers: ["severity = info"]
              - target_matchers: ["alertname = InfoInhibitor"]
            receivers:
              - name: "null"
              - name: email-alerts
                email_configs:
                  - to: quangphongnguyen147@gmail.com
                    send_resolved: true
            route:
              group_by: ["namespace"]
              group_wait: 30s
              group_interval: 5m
              receiver: "null"
              repeat_interval: 12h
              routes:
                - matchers: ["alertname = Watchdog"]
                  receiver: "null"
                - matchers: ["alertname = APISuccessRateLow"]
                  receiver: email-alerts
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
